from typing import Union


def install(name: str) -> Union[str, bool]: ...
def pre_upgrade(name: str) -> Union[str, bool]: ...
def post_upgrade(name: str) -> Union[str, bool]: ...
def remove(name: str) -> Union[str, bool]: ...
